import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#f8f9ff",
        surface: "#f8f9ff",
        "surface-bright": "#f8f9ff",
        "surface-dim": "#ccdbf2",
        "surface-lowest": "#ffffff",
        "surface-low": "#eef4ff",
        "surface-container": "#e5efff",
        "surface-high": "#dbe9ff",
        "surface-highest": "#d4e4fa",
        "surface-variant": "#d4e4fa",
        "on-surface": "#0d1c2d",
        "on-surface-variant": "#3d4947",
        "on-background": "#0d1c2d",
        outline: "#6d7a77",
        "outline-variant": "#bcc9c6",
        primary: "#00685f",
        "primary-container": "#008378",
        "on-primary": "#ffffff",
        "on-primary-container": "#f4fffc",
        "primary-fixed": "#89f5e7",
        "primary-fixed-dim": "#6bd8cb",
        "inverse-primary": "#6bd8cb",
        secondary: "#515f74",
        "secondary-container": "#d5e3fc",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#57657a",
        "secondary-fixed": "#d5e3fc",
        "secondary-fixed-dim": "#b9c7df",
        "on-secondary-fixed": "#0d1c2e",
        "on-secondary-fixed-variant": "#3a485b",
        tertiary: "#545c72",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "inverse-surface": "#233143",
        "inverse-on-surface": "#e9f1ff",
        estimated: "#94a3b8",
        actual: "#00685f",
        /** Brass — money totals / Cash MHR that should pop (not purple, not cream-terracotta). */
        accent: "#a16207",
        "accent-container": "#fef3c7",
        "on-accent": "#ffffff",
        "on-accent-container": "#422006",
        /** Steel blue — secondary rails / table headers / info panes. */
        info: "#1e4d6b",
        "info-container": "#e2eef5",
        "on-info": "#ffffff",
        "on-info-container": "#0c2a3d",
        /** Soft fill for ₹ input cells. */
        "money-tint": "#f4faf8",
        signal: "#c27803",
      },
      fontFamily: {
        sans: ["var(--font-public-sans)", "system-ui", "sans-serif"],
        mono: ["var(--font-jetbrains-mono)", "ui-monospace", "monospace"],
      },
      fontSize: {
        "headline-lg": [
          "28px",
          { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-md": [
          "20px",
          { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "code-md": ["13px", { lineHeight: "16px", fontWeight: "500" }],
        "code-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
        "label-caps": [
          "11px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" },
        ],
      },
      spacing: {
        gutter: "16px",
        sidebar: "240px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.125rem",
        md: "0.375rem",
        lg: "0.5rem",
      },
      boxShadow: {
        industrial: "0 2px 4px rgba(0,0,0,0.05)",
        sticky: "0 -4px 6px -1px rgba(0,0,0,0.05)",
      },
    },
  },
  plugins: [],
} satisfies Config;
